# services:
#   postgres:
#     image: postgres:latest
#     container_name: gptchat_container
#     restart: always
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: gptchat_db

# volumes:
#   db-data:

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    # Expose the Postgres port to the host machine,
    # so you can inspect and administrate it
    ports:
      - "54320:5432"
  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    platform: linux/arm64/v8
    environment:
      APPEND_PORT: "postgres:5432"
      ALLOW_ADDR_REGEX: ".*"
      LOG_TRAFFIC: "true"
    ports:
      # Expose the WebSocket proxy port to the host machine,
      # this is where @vercel/postgres will connect
      - "54330:80"
    depends_on:
      - postgres
