import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import * as stylex from "@stylexjs/stylex";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      {...stylex.props(styles.html, styles.reset)}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        {...stylex.props(styles.reset)}
      >
        {children}
      </body>
    </html>
  );
}

const DARK = "@media (prefers-color-scheme: dark)";

const styles = stylex.create({
  html: {
    fontFamily: "system-ui, sans-serif",
    backgroundColor: "white",
    color: "black",
    [DARK]: {
      backgroundColor: "black",
      color: "white",
    },
  },
  reset: {
    minHeight: "100%",
    margin: 0,
    padding: 0,
  },
});
